### PR TITLE
Merge Playground and Light into single app

### LINKED ISSUE #121: Playground support for Dark Mode
We should consider in two options:

№1 Set in `info.plist` information that apps can [use only `Ligth` mode](https://medium.com/@akshay.s.somkuwar/disable-dark-mode-in-ios-13-for-your-ios-app-c025b446d87b)

image
image

№2 Or Fix colors when they looks wrong because in some places it looks nice with dark mode:

image
image

### PR DESCRIPTION
**Pull request by mgierlasinski**
Resolves #121

### CODE REVIEW

File: Playground/Playground/Features/Editor/Handlers/RadialHandler.cs [hunk 1]
```diff
@@ -0,0 +1,176 @@
...
+            _isCustomSize = RadiusX > 0 || RadiusY > 0;
+
+            RaisePropertyChanged(nameof(CenterX));
+            RaisePropertyChanged(nameof(CenterY));
+            RaisePropertyChanged(nameof(RadiusX));
+            RaisePropertyChanged(nameof(RadiusY));
+            RaisePropertyChanged(nameof(Shape));
+            RaisePropertyChanged(nameof(SizeOne));
+            RaisePropertyChanged(nameof(SizeTwo));
+            RaisePropertyChanged(nameof(IsCustomSize));
```
Comment (bbenetskyy) [inline Playground/Playground/Features/Editor/Handlers/RadialHandler.cs:107]: Maybe just replace with `RaiseAllPropertyChanged`?

File: Playground/Playground/Features/Gallery/GalleryListViewModel.cs [hunk 2]
```diff
@@ -28,11 +28,11 @@ public string Title
         public string CategoryTag
         {
             get => _categoryTag;
-            set => SetProperty(ref _categoryTag, value, onChanged: () =>
+            set => SetProperty(ref _categoryTag, value, () =>
             {
                 Title = _categoryService.GetCategories().FirstOrDefault(x => x.Tag == _categoryTag)?.Name;
                 _allGradients = _galleryService.GetGradients(_categoryTag).ToList();
-                RefreshGradients();
+                //LoadGradients();
```
Comment (bbenetskyy) [inline Playground/Playground/Features/Gallery/GalleryListViewModel.cs:35]: Maybe this should be uncommented?

File: Playground/Playground/Playground.csproj [hunk 3]
```diff
@@ -9,10 +9,21 @@
     <DebugSymbols>true</DebugSymbols>
   </PropertyGroup>
 
+  <ItemGroup>
+    <None Remove="Resources\Fonts\IcoMoon.ttf" />
+  </ItemGroup>
```
Comment (bbenetskyy) [inline Playground/Playground/Playground.csproj:14]: This can be removed, below it's added as `EmbeddedResource`

**Review by bbenetskyy — APPROVED** [review]

File: Playground/Playground/Features/Editor/Handlers/RadialHandler.cs (hunk 1 above)
Comment (mgierlasinski) [reply Playground/Playground/Features/Editor/Handlers/RadialHandler.cs:107]: This is not MvvmCross :) `RaisePropertyChanged` is implemented by us and we don't have `RaiseAllPropertyChanged`.

File: Playground/Playground/Features/Gallery/GalleryListViewModel.cs (hunk 2 above)
Comment (mgierlasinski) [reply Playground/Playground/Features/Gallery/GalleryListViewModel.cs:35]: It's called from Page code behind to workaround issue on UWP - if you load data too early (before Layout is measured) you will see empty screen.

File: Playground/Playground/Playground.csproj (hunk 3 above)
Comment (mgierlasinski) [reply Playground/Playground/Playground.csproj:14]: That was added by VS - by default, all files in directory are added to project (in new csproj). Because ttf is not something compiled, it's added just like file (None means no action). This is why it's being removed before added again as EmbeddedResource to avoid adding same file 2 times. I didn't try to manually remove but let's leave it.
